export enum money {
    USD = "USD",
    EUR = "EUR",
    COP = "COP",
    ARS = "ARS",
    PEN = "PEN",
    CLP = "CLP",
    MXN = "MXN",
    BRL = "BRL",
    UYU = "UYU",
    PYG = "PYG",
    BOB = "BOB",
    VEF = "VEF",
    GYD = "GYD",
    SRD = "SRD",
    ANG = "ANG",
    HTG = "HTG",
    JMD = "JMD",
    BSD = "BSD",
    BBD = "BBD",
    TTD = "TTD",
    XCD = "XCD",
    BZD = "BZD",
    KYD = "KYD",
    BMD = "BMD",
    FKP = "FKP",
    GIP = "GIP",
    SHP = "SHP",
    JEP = "JEP",
    IMP = "IMP"
}

export enum Cryptocurrencies {
    USDT = "USDT",
    Bitcoin = "BTC",
    Ethereum = "ETH",
    BinanceCoin = "BNB",
    Tether = "USDT",
    Cardano = "ADA",
    Ripple = "XRP",
    Solana = "SOL",
    Dogecoin = "DOGE",
    Polkadot = "DOT",
    Litecoin = "LTC",
    Avalanche = "AVAX",
    Chainlink = "LINK",
    Stellar = "XLM",
    Uniswap = "UNI",
    Monero = "XMR",
    Cosmos = "ATOM",
    Algorand = "ALGO",
    VeChain = "VET",
    Tezos = "XTZ",
    Aave = "AAVE"
  }
  